server:
  port: 8081

spring:
  application:
    name: gateway

  cloud:
      gateway:
        mvc:
          routes:
            - id: syntax-error-studios
              uri: lb://SYNTAX_ERROR_STUDIOS
              predicates:
                - Path=/api/**
            
            - id: syntax-error-studios-docs
              uri: lb://SYNTAX_ERROR_STUDIOS
              predicates:
                - Path=/v3/api-docs/**

            - id: syntax-error-studios-swagger
              uri: lb://SYNTAX_ERROR_STUDIOS
              predicates:
                - Path=/swagger-ui/**

            - id: syntax-error-studios-doc
              uri: lb://SYNTAX_ERROR_STUDIOS
              predicates:
                - Path=/doc/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka