server.port=8081

spring.application.name=gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=syntax
spring.cloud.gateway.routes[0].uri=lb://SYNTAX_ERROR_STUDIOS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[1].id=docs
spring.cloud.gateway.routes[1].uri=lb://SYNTAX_ERROR_STUDIOS
spring.cloud.gateway.routes[1].predicates[0]=Path=/doc/**

spring.cloud.gateway.routes[2].id=openapi
spring.cloud.gateway.routes[2].uri=lb://SYNTAX_ERROR_STUDIOS
spring.cloud.gateway.routes[2].predicates[0]=Path=/v3/api-docs/**